### ISSUE TITLE
Outstanding issues with the pr2-kinect2-config package

### ISSUE THREAD

**Issue by TheDash** [pr2-debs/pr2-kinect2-config#17]
@archielee can you comment on any issues that are known with this package?
@rahulraw if you have time, feel free to comment/add to discussion

- [x] Investigate how to integrate transforms from kinect2_bridge frames into the general PR2 model

**Comment by archielee** [comment]
Current issues:

Must keep "publish_tf" param in launch file for kinect2_bridge as "true"
Must add param tag to set "base_name_tf" to "head_mount_kinect2" so they match with urdf model

**Comment by TheDash** [comment]
@archielee please add the transform issue of the PR2 NUC images to the PR2 (integration)
